### ISSUE TITLE
HELLO I WANT EXACT SAME FORK OF THIS PROJECT

### ISSUE THREAD

**Issue by Hajeck** [arunavo4/sol-sell-escrow#3]
Hello, I am interested in ordering your service. I want to develop an escrow secured website on solana blockchain that connects buyers and sellers in a secured way. If you're interested in working with me contact me on whatsapp https://wa.link/6kkmz5

**Comment by arunavo4** [comment]
We can connect, send me and email and we can talk details. Email is on my GitHub profile. @Hajeck
